import { ScoreMessage } from "./chat/types";
import styles from "./PdfPreview.module.css";

interface Props {
  scores: ScoreMessage[];
  url: string | null;
  onDownload: () => void;
}

export default function PdfPreview({ scores, url, onDownload }: Props) {
  const hostname = url ? new URL(url).hostname : null;
  const seo = scores.find((s) => s.scoreType === "SEO");
  const aio = scores.find((s) => s.scoreType === "AIO");

  return (
    <div className={styles.panel}>
      <span className="eyebrow">Report preview</span>
      <div className={styles.doc}>
        {hostname ? (
          <>
            <div className={styles.docTitle}>
              {hostname} — SEO {aio ? "& AIO " : ""}Audit
            </div>
            <div className={styles.divider} />
            <div className={styles.generatedBy}>
              Generated by Rank Buddy · Prometheus Tools
            </div>
            {seo && (
              <div className={styles.section}>
                <div className={styles.sectionHead}>SEO Score</div>
                <div className={styles.bigScore}>{seo.score}/100</div>
                {seo.doing_well && seo.doing_well.length > 0 && (
                  <>
                    <div className={styles.subHead}>Doing well</div>
                    {seo.doing_well.map((item, i) => (
                      <div key={i} className={styles.item}>· {item}</div>
                    ))}
                  </>
                )}
                {seo.needs_work && seo.needs_work.length > 0 && (
                  <>
                    <div className={styles.subHead}>Needs work</div>
                    {seo.needs_work.map((item, i) => (
                      <div key={i} className={styles.item}>· {item}</div>
                    ))}
                  </>
                )}
                {seo.top_fixes && seo.top_fixes.length > 0 && (
                  <>
                    <div className={styles.subHead}>Top fixes</div>
                    {seo.top_fixes.map((item, i) => (
                      <div key={i} className={styles.item}>{i + 1}. {item}</div>
                    ))}
                  </>
                )}
              </div>
            )}
            {aio && (
              <div className={styles.section}>
                <div className={styles.sectionHead}>AIO Score</div>
                <div className={styles.bigScore}>{aio.score}/100</div>
                {aio.visible_to_ai && aio.visible_to_ai.length > 0 && (
                  <>
                    <div className={styles.subHead}>Visible to AI</div>
                    {aio.visible_to_ai.map((item, i) => (
                      <div key={i} className={styles.item}>· {item}</div>
                    ))}
                  </>
                )}
                {aio.invisible_to_ai && aio.invisible_to_ai.length > 0 && (
                  <>
                    <div className={styles.subHead}>Invisible to AI</div>
                    {aio.invisible_to_ai.map((item, i) => (
                      <div key={i} className={styles.item}>· {item}</div>
                    ))}
                  </>
                )}
                {aio.blunt_insight && (
                  <div className={styles.insight}>"{aio.blunt_insight}"</div>
                )}
              </div>
            )}
            {!aio && seo && (
              <div className={styles.aioPlaceholder}>
                <div className={styles.sectionHead}>AIO Score</div>
                <div className={styles.pending}>— Pending analysis</div>
              </div>
            )}
          </>
        ) : (
          <div className={styles.empty}>
            Run an audit to see the report preview here.
          </div>
        )}
      </div>
      {hostname && (
        <button className={styles.download} onClick={onDownload}>
          ↓ Download Report
        </button>
      )}
    </div>
  );
}
