import { NextRequest } from "next/server";

export async function GET(req: NextRequest) {
  const url = req.nextUrl.searchParams.get("url");
  if (!url) {
    return new Response("Missing url param", { status: 400 });
  }

  let hostname = url;
  try {
    hostname = new URL(url).hostname;
  } catch {
    // use as-is
  }

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${hostname} — SEO & AIO Audit</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: Georgia, serif;
      background: #EFEBE8;
      color: #1C1C1C;
      padding: 48px;
      max-width: 800px;
      margin: 0 auto;
    }
    .eyebrow {
      font-family: monospace;
      font-size: 0.65rem;
      letter-spacing: 0.15em;
      text-transform: uppercase;
      color: #FF5B23;
      font-weight: 600;
    }
    h1 {
      font-size: 2rem;
      font-weight: 400;
      margin: 10px 0 4px;
      line-height: 1.1;
    }
    .meta {
      font-family: monospace;
      font-size: 0.65rem;
      color: #525252;
      letter-spacing: 0.05em;
      margin-bottom: 32px;
    }
    .divider { height: 1px; background: #DCD8D4; margin: 20px 0; }
    .section { margin-bottom: 32px; }
    .section-head {
      font-family: monospace;
      font-size: 0.65rem;
      letter-spacing: 0.12em;
      text-transform: uppercase;
      color: #FF5B23;
      font-weight: 700;
      margin-bottom: 8px;
    }
    .score-num {
      font-size: 3rem;
      color: #FF5B23;
      font-weight: 400;
      line-height: 1;
      margin-bottom: 16px;
    }
    .score-num .denom {
      font-size: 1.2rem;
      color: #525252;
    }
    .sub-head { font-weight: 600; font-size: 0.85rem; margin: 12px 0 4px; }
    ul, ol { padding-left: 20px; }
    li { margin-bottom: 4px; font-size: 0.88rem; line-height: 1.5; color: #525252; }
    .insight {
      font-style: italic;
      border-left: 2px solid #FF5B23;
      padding-left: 12px;
      margin-top: 12px;
      color: #525252;
    }
    .footer {
      margin-top: 48px;
      padding-top: 16px;
      border-top: 1px solid #DCD8D4;
      font-family: monospace;
      font-size: 0.6rem;
      color: #A8A29E;
      letter-spacing: 0.08em;
    }
  </style>
</head>
<body>
  <div class="eyebrow">Rank Buddy · Prometheus Tools</div>
  <h1>${hostname} — SEO &amp; AIO Audit</h1>
  <div class="meta">Generated ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })} · rank-buddy.v1</div>
  <div class="divider"></div>
  <p style="color: #525252; font-size: 0.9rem; line-height: 1.6; margin-bottom: 24px;">
    This report was generated by Rank Buddy using evidence-only scoring. Only verifiable content from the pages reviewed was used. No assumptions were made about traffic, backlinks, or rankings.
  </p>
  <div class="section">
    <div class="section-head">SEO Analysis</div>
    <p style="color: #525252; font-size: 0.88rem;">Complete your audit in the Rank Buddy tool to populate this section.</p>
  </div>
  <div class="section">
    <div class="section-head">AIO Analysis</div>
    <p style="color: #525252; font-size: 0.88rem;">Run the AIO analysis after your SEO audit to populate this section.</p>
  </div>
  <div class="footer">prometheus.today/tools/rank-buddy · Generated by Rank Buddy v1</div>
</body>
</html>`;

  return new Response(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `attachment; filename="rank-buddy-${hostname}.html"`,
    },
  });
}
